[package]
name = "martini-bot"
version = "0.1.0"
authors = ["Lukas Kalbertodt <lukas.kalbertodt@gmail.com>"]


[dependencies]
regex_macros = "*"
rustc-serialize = "*"
telegram-bot = "*"
itertools = "*"
strsim = "*"

[dependencies.regex]
version = "*"
features = ["pattern"]
